### ISSUE TITLE
alignment file not read

### ISSUE THREAD

**Issue by Jigyasa3** [genomewalker/oligo4fun#3]
I am trying the oligo4fun tutorial on my dataset, which is made of COG0202 protein coding genes extracted from metagenome sequencing.
When I read the alignment file (constructed using mafft alignment), it gives the following error-
> saturation_estimate<-estimate_saturation(aln,nseqs=500,model="K80",all=FALSE)
Error: Looks like your sequences is not in the correct frame. Please predict the ORFs on your sequence and provide the correct nuclotide file.

My nucleotide sequences are in correct ORF, as I extracted theses sequences using [fetchM](https://sunagawalab.ethz.ch/motu-tool/tutorial.motu.standalone.html) perl script.

**Comment by genomewalker** [comment]
Hi
can you share your alignment?

Cheers

**Comment by Jigyasa3** [comment]
[all-COG0202.genus.Treponema.microcerotermes.aligned.fasta.txt](https://github.com/genomewalker/oligo4fun/files/2689505/all-COG0202.genus.Treponema.microcerotermes.aligned.fasta.txt)

**Comment by genomewalker** [comment]
You should first align at the AA level and then backtranslate to have a codon-based alignment. Similar to what [PAL2NAL](http://www.bork.embl.de/pal2nal/) does. If once aligned you can send me back the codon-based alignment I will run a couple of tests. Never tried it with sequences coming from metagenomes.

**Comment by Jigyasa3** [comment]
thanks! I will try it.
